### ISSUE TITLE
ekam-bootstrap can't be ccached 

### ISSUE THREAD

**Issue by abliss** [capnproto/ekam#26]
On my machine, compiling the bootstrap ekam takes 88sec. On a github runner, it's around 25sec. It could be sped up by ccache, but ccache can't compile multiple source files on one commandline. I'd like to replace the bootstrap's Makefile recipe to compile each source file separately and then link them together.

**Comment by kentonv** [comment]
Hmm, compiling the bootstrap ekam is something that you shouldn't have to repeat, though. So what use is it to ccache it?

**Comment by abliss** [comment]
Every time I start dev on a new machine, or run a clean build, or initialize a new build tree, or run a hermetic build in a container....
Also, the compilation units could be done in parallel under `make -j`, which ought to speed up the first bootstrap even if you never do repeat it.
