### ISSUE TITLE
Error building with glibc 2.33 because of _STAT_VER changes

### ISSUE THREAD

**Issue by bretthoerner** [capnproto/ekam#36]
The glibc maintainers have done something with the `stat` wrappers in 2.33: https://github.com/bminor/glibc/commit/8ed005daf0ab03e142500324a34087ce179ae78e

While running `make` to build `ekam` under glibc 2.33:
```
✘ learn: ekam/rules/intercept.ekam-rule
    src/ekam/rules/intercept.c: In function ‘direct_stat’:
    src/ekam/rules/intercept.c:671:21: error: ‘_STAT_VER’ undeclared (first use in this function)
      671 |   return real_xstat(_STAT_VER, path, sb);
          |                     ^~~~~~~~~
    src/ekam/rules/intercept.c:671:21: note: each undeclared identifier is reported only once for each function it appears in
    src/ekam/rules/intercept.c:672:1: warning: control reaches end of non-void function [-Wreturn-type]
      672 | }
          | ^
```

The `intercept.c` line in question: https://github.com/capnproto/ekam/blob/454152e658db071f62a45eae620ef244c1726165/src/ekam/rules/intercept.c#L671

Note that `ekam` previously built on the same Linux install but a glibc upgrade broke compilation as seen above, so I suspect this issue is coming to Debian/Ubuntu eventually.

For now, I built an `ekam` binary in a Docker container using an older glibc, and I replaced the `_STAT_VER` in my host system's `intercept.c` with `3` and things seem to work. I figured I'd put this up now for anyone else Googling. I'm a bit out of my depth on what's going on in that glibc change, or why `_STAT_VER` didn't make it into _anything_ under my `/usr/include` (I have no `xstatver.h`, for example), but I'll try to poke at it some more in a bit.

**Comment by kentonv** [comment]
See attempted fix in #37, but I don't actually have the new version of glibc to test this on.
