### ISSUE TITLE
Build fails in /tmp

### ISSUE THREAD

**Issue by zenhack** [capnproto/ekam#57]
@garrison and I worked out that the underlying source of our problems getting ekam to build with nix is that ekam fails to build when building under `/tmp`; I can verify that it fails in the same way if I just do the normal build process in `/tmp`:

```
cd /tmp
git clone https://github.com/capnproto/ekam
cd ekam
make
```
The errors are complaints about not being able to find various files; full build log attached.

[build.log](https://github.com/capnproto/ekam/files/7190175/build.log)

**Comment by zenhack** [comment]
(My first instinct was that maybe the tmpfs was running out of space or something, killing some crucial process, but I monitored both its space usage and available memory and resource use of both was quite modest).

**Comment by garrison** [comment]
This looks suspcious:

https://github.com/capnproto/ekam/blob/dc414bbdb4f0164c196dc91921ad27241efaa0cc/src/ekam/rules/intercept.c#L526-L530

considering

https://github.com/capnproto/ekam/blob/dc414bbdb4f0164c196dc91921ad27241efaa0cc/src/ekam/rules/intercept.c#L439-L447

**Comment by zenhack** [comment]
That does seem suspicious. I tried the below, but no dice, same error. I may stare at it more later.

```
diff --git a/src/ekam/rules/intercept.c b/src/ekam/rules/intercept.c
index 3fc5a3a..c70bb0a 100644
--- a/src/ekam/rules/intercept.c
+++ b/src/ekam/rules/intercept.c
@@ -437,6 +437,16 @@ static bool bypass_remap(const char *pathname) {
 }
 
 static bool is_temporary_dir(const char *pathname) {
+  size_t cwd_len = strlen(current_dir);
+  if (strncmp(pathname, current_dir, cwd_len) == 0
+      && (pathname[cwd_len] == '/' || pathname[cwd_len] == '\0')) {
+    // Somewhere under our working directory. If our working directory happens
+    // to be inside one of the temporary dirs, then we need to be careful to
+    // *not* treat this as a temporary file, otherwise this will apply to basicaly
+    // everything, and strange things will happen.
+    return false;
+  }
+
   // TODO(soon): Simplify the logic to use `path_has_prefix`.
   if (strcmp(pathname, TMP) == 0 ||
       strcmp(pathname, VAR_TMP) == 0 ||
```

**Comment by kentonv** [comment]
I think @garrison is on the right track here. It's the virtual filesystem logic in the interceptor that doesn't expect the code to live under `/tmp`. I am not sure why @zenhack's change didn't work but it seems like the right direction.

**Comment by garrison** [comment]
I disabled the `debug` check on the `fprintf` line in the code block I posted above, and I get a lot of `temp file: /tmp/ekam` (the base directory of the clone).

I think this `strcat` is the reason @zenhack's patch does not work:

https://github.com/capnproto/ekam/blob/dc414bbdb4f0164c196dc91921ad27241efaa0cc/src/ekam/rules/intercept.c#L252

**Comment by zenhack** [comment]
Good catch! Can confirm this works for me too. I'll open a pr.

> EDIT 2: Yes, it works for me now. But it might act a bit weird if the base directory of the build were / (which is a bit of a pathological case, probably shouldn't be expected to work).

Yeah, this would mean that `/proc` and `/tmp` would be underneath the working directory. I don't think we should attempt to support that.
